DROP DATABASE chat;
CREATE DATABASE chat;

USE chat;

CREATE TABLE USERS (
	id INT AUTO_INCREMENT,
	username VARCHAR(32) NOT NULL,
	password VARCHAR(512) NOT NULL,
	PRIMARY KEY(id)
) ENGINE=InnoDB;

CREATE TABLE CHATS (
	id INT AUTO_INCREMENT,
	name VARCHAR(32) NOT NULL,
	userId INT NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(userId) REFERENCES USERS(id)
) ENGINE=InnoDB;

CREATE TABLE MESSAGES (
	id INT AUTO_INCREMENT,
	text VARCHAR(1000) NOT NULL,
	chat VARCHAR(32) NOT NULL,
	userId INT NOT NULL,
	date DATETIME NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(userId) REFERENCES USERS(id)
) ENGINE=InnoDB;
